Jomial_Proiektua/Jomial_Final/Models/Hotel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Jomial_Final.Models
{
    public class Hotel
    {
        public String Id { get; set; }
        public String izena { get; set; }
        public int postaKodea { get; set; }
        public String distantzia { get; set; }
        public String kokalekua { get; set; }
        public String herrialdea { get; set; }
        public String helbidea { get; set; }
        public int izarrak { get; set; }
        public double kalifikazioa { get; set; }
        public List<Argazkia> argazkiak { get; set; }
        public String info { get; set; }
        public String infoGenerala { get; set; }    
        public List<Gelak> gelak { get; set; }
        public List<String> zerbitzuak { get; set; }

    }
}

Jomial_Proiektua/Jomial_Final/Controllers/BilatuController.cs
using Jomial_Final.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Jomial_Final.Controllers
{
    public class BilatuController : Controller
    {
        // GET: Bilatu
        string Baseurl = "http://localhost:8080/api/";

        [HttpPost]
        public async Task<ActionResult> BusquedaHotel(FormCollection collection)
        {
            try
            {

                String hotelIzena = collection["hotelIzena"];
                ViewData["hotelIzena"] = hotelIzena;

                String hotelDataIn = collection["dataIn"];
                ViewData["dataIn"] = hotelDataIn;

                String hotelDataOut = collection["dataOut"];
                ViewData["dataOut"] = hotelDataOut;

                String huespe = collection["huespe"];
                ViewData["huespe"] = huespe;

                String days = collection["days"];
                ViewData["days"] = days;

                List<Hotel> hotel = new List<Hotel>();

                using (var client = new HttpClient())
                {
                    //Passing service base url  
                    client.BaseAddress = new Uri(Baseurl);

                    client.DefaultRequestHeaders.Clear();
                    //Define request data format  
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                    HttpResponseMessage Res = await client.GetAsync("hotels/kokalekua?kokalekua=" + hotelIzena);

                    //Checking the response is successful or not which is sent using HttpClient  
                    if (Res.IsSuccessStatusCode)
                    {

                        var EmpResponse = Res.Content.ReadAsStringAsync().Result;

                        hotel = JsonConvert.DeserializeObject<List<Hotel>>(EmpResponse);


                    }

                    return View(hotel);

                }
            }
            catch
            {
                return null;
            }

        }
        public async Task<ActionResult> Hotel(String id)
        {
            try
            {


                Hotel hotel2 = new Hotel();
                List<Hotel> hotela = new List<Hotel>();

                using (var client = new HttpClient())
                {
                    //Passing service base url  
                    client.BaseAddress = new Uri(Baseurl);

                    client.DefaultRequestHeaders.Clear();
                    //Define request data format  
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                    HttpResponseMessage Res = await client.GetAsync("hotel/" + id);

                    //Checking the response is successful or not which is sent using HttpClient  
                    if (Res.IsSuccessStatusCode)
                    {
                        //Storing the response details recieved from web api   
                        var EmpResponse = Res.Content.ReadAsStringAsync().Result;

                        hotel2 = JsonConvert.DeserializeObject<Hotel>(EmpResponse);
                        hotela.Add(hotel2);

                    }
                    return View(hotela);
                }
            }
            catch
            {
                return null;
            }

        }
        [HttpPost]
        public ActionResult Txartela(FormCollection collection)
        {
            try
            {

                String hotelDataIn = collection["dataIn"];
                ViewData["dataIn"] = hotelDataIn;

                String hotelDataOut = collection["dataOut"];
                ViewData["dataOut"] = hotelDataOut;

                String huespe = collection["huespe"];
                ViewData["huespe"] = huespe;

                String price = collection["price"];
                String[] x = price.Split('-');


                ViewData["hotel_izena"] = x[0];

                ViewData["price"] = x[1];

                String days = collection["days"];
                Session["days-1"] = days;
                return View();
            }
            catch
            {
                return null;
            }
        }

        [HttpPost]
        public async Task<ActionResult> Book(FormCollection collection)
        {
            try
            {


                List<Errenta> errenta = new List<Errenta>();

                String hasiera_data = collection["hasiera_data"];
                String amaiera_data = collection["amaiera_data"];
                String hotel_izena = collection["hotel_izena"];
                double prezioTotala = Double.Parse(collection["prezioTotala"]);

                String erabiltzailea_emaila = collection["erabiltzailea_emaila"];
                Session["erabiltzailea_emaila"] = erabiltzailea_emaila;
                int txartel_zenbakia = Int32.Parse(collection["txartel_zenbakia"]);

                String txartel_titularra = collection["txartel_titularra"];

                String txartel_iraunginpena = collection["txartel_iraunginpena"];

                int txartel_cvv = Int32.Parse(collection["txartel_cvv"]);

                Errenta errent = new Errenta(hasiera_data, amaiera_data, hotel_izena, prezioTotala, erabiltzailea_emaila, txartel_zenbakia, txartel_titularra, txartel_iraunginpena, txartel_cvv);

                using (var client = new HttpClient())
                {
                    //Passing service base url  
                    client.BaseAddress = new Uri(Baseurl);

                    client.DefaultRequestHeaders.Clear();
                    //Define request data format  
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    var postTask = client.PostAsJsonAsync<Errenta>("errenta/", errent);
                    postTask.Wait();
                    var res = postTask.Result;
                    var result = postTask.Result;

                    HttpResponseMessage Res = await client.GetAsync("errenta/emaila?emaila=" + erabiltzailea_emaila);



                    if (Res.IsSuccessStatusCode && res.IsSuccessStatusCode)
                    {

                        var EmpResponse = Res.Content.ReadAsStringAsync().Result;

                        errenta = JsonConvert.DeserializeObject<List<Errenta>>(EmpResponse);
                        return View(errenta);

                    }
                    return View();

                }
            }
            catch
            {
                return null;
            }
        }
        public async Task<ActionResult> allBooks(string email)
        {
            try
            {

                List<Errenta> errenta = new List<Errenta>();
                List<Hotel> hotela = new List<Hotel>();

                using (var client = new HttpClient())
                {
                    //Passing service base url  
                    client.BaseAddress = new Uri(Baseurl);

                    client.DefaultRequestHeaders.Clear();
                    //Define request data format  
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                    HttpResponseMessage Res = await client.GetAsync("errenta/emaila?emaila=" + email);

                    //Checking the response is successful or not which is sent using HttpClient  

                    if (Res.IsSuccessStatusCode && Res.IsSuccessStatusCode)
                    {

                        var EmpResponse = Res.Content.ReadAsStringAsync().Result;

                        errenta = JsonConvert.DeserializeObject<List<Errenta>>(EmpResponse);
                        return View(errenta);

                    }
                    return View();
                }
            }
            catch
            {
                return null;
            }



        }
        // GET: Bilatu/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Bilatu/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Bilatu/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Bilatu/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Bilatu/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Bilatu/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Bilatu/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

Jomial_Proiektua/Jomial_Final/Views/Bilatu/Book.cshtml
<link rel="stylesheet" href="~/Content/stylesBook.css">
<title>Completa tu Reserva</title>
@model IEnumerable<Jomial_Final.Models.Errenta>
<header id="myHeader">
    <nav class="navbar navbar bg justify-content-between">
        <a class="navbar-brand" href="@Url.Action("IndexLog", "Home")"><img src="~/Imagenes/logo.png"></a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("allBooks", "Bilatu" ,  new {email =Session["erabiltzailea_emaila"]})"> <strong>  @Session["erabiltzaile"] </strong></a>
                <a class="nav-link" href="@Url.Action("Index", "Home")">Cerrar Sesion</a>
            </li>
        </ul>
    </nav>
</header>
<div class="mensajea">
    <h1>
        SE HA COMPLETADO TU RESERVA
    </h1><br>
    <h4>Gracias por confiar en nosotros</h4>
</div>
@foreach (var item in Model)
{
    <div class="pricing-box-container">
        <div class="pricing-box text-center">
            <h5>@Html.DisplayFor(modelItem => item.hotel_izena)</h5>
            <p class="price"><sup>€</sup>@Html.DisplayFor(modelItem => item.prezio_total)<sub>/noche</sub></p>
            <ul class="features-list">
                <li><strong>Fecha de entrada: </strong> @Html.DisplayFor(modelItem => item.hasiera_data)</li>
                <li><strong>Fecha de salida: </strong>  @Html.DisplayFor(modelItem => item.amaiera_data)</li>
                <li><strong>Correo electronico: </strong> @Html.DisplayFor(modelItem => item.emaila)</li>
            </ul>

        </div>
    </div>
}

Jomial_Proiektua/Jomial_Final/Views/Bilatu/BusquedaHotel.cshtml
<link rel="stylesheet" href="~/Content/styles.css">
<title>Encuentra tu hotel</title>
@model IEnumerable<Jomial_Final.Models.Hotel>

<header id="myHeader">
    <nav class="navbar1 navbar bg justify-content-between">
        <a class="navbar-brand" href="@Url.Action("IndexLog", "Home")"><img src="~/Imagenes/logo.png"></a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("allBooks", "Bilatu" ,  new {email =Session["erabiltzailea_emaila"]})"> <strong>  @Session["erabiltzaile"] </strong></a>
                <a class="nav-link" href="@Url.Action("Index", "Home")">Cerrar Sesion</a>
            </li>
        </ul>
    </nav>
</header>
<section>
    <div class="containerHandia">
        <h5>Más de 300 alojamientos</h5>
        <h2>Encuentra lugares para hospedarte cerca de ti</h2>
        <h6>Antes de reservar, revisa las restricciones de viaje relacionadas con el coronavirus.<a href="https://es.wikipedia.org/wiki/Pandemia_de_COVID-19">Más información</a></h6><br>
        <div class="containerTxikia">
            <h4><strong>@ViewData["hotelIzena"]</strong></h4><span class="infogeneral"><strong>Fecha de entrada: </strong> @ViewData["dataIn"] · <strong>Fecha de salida: </strong> @ViewData["dataOut"] · <strong>Huespedes: </strong> @ViewData["huespe"] · <strong>Noches: </strong> @ViewData["days"]</span><br><br>
            @foreach (var item in Model)
            {
        <a href="@Url.Action("Hotel", "Bilatu", new {id =item.Id})">
            <div class="info">
                @{
                    var fuente = item.argazkiak.First().argazkia + ".png";

                }
                @{
                    Session["daysnight"] = @ViewData["days"];
                    var total = item.gelak.First().kostuGaua *Convert.ToDouble(Session["daysnight"]);

                }
                <img src="~/Imagenes/FotosHotel/@fuente" /><br>
                <p style="padding-top: 10px;"><img style="width: 20px;height: 20px;display: inline; vertical-align: text-top;" src="~/Imagenes/iconfinder_star_326703 (1).png"><strong style="padding-top: 12px;">@Html.DisplayFor(modelItem => item.izarrak)</strong>(326)</p>
                <h4>@Html.DisplayFor(modelItem => item.izena)</h4>
                <h3><strong>Calificaion de nuestros clientes: </strong> @Html.DisplayFor(modelItem => item.kalifikazioa)</h3>

                <h4><strong>@Html.DisplayFor(modelItem => item.gelak.First().kostuGaua)€</strong> - por noche.</h4>
                <h6><strong>Total: </strong>@total€</h6>
            </div>
        </a>
            }

        </div>

    </div>
</section>
<br>
<section id="mysection">
    <table cellpadding="0" cellspacing="0" width="100%">
        <tr>
            <td>Valladolid<br /><img src="~/Imagenes/valladolid.jpg" /></td>
            <td>León<br /><img src="~/Imagenes/leon.jpg" /></td>
            <td>Segovia<br /><img src="~/Imagenes/segovia.jpg" /></td>
            <td>Cáceres<br /><img src="~/Imagenes/caceres.jpg" /></td>
        </tr>
        <tr>

            <td>Ávila<br /><img src="~/Imagenes/avila.jpg" /></td>
            <td>Guadalajara<br /><img src="~/Imagenes/guadalajara.jpg" /></td>
            <td>Cuenca<br /><img src="~/Imagenes/cuenca.jpg" /></td>
            <td>Alcalá de Henares<br /><img src="~/Imagenes/alcala.jpg" /></td>
        </tr>
    </table>
</section>
<br>

<div class="container-fluid pb-0 mb-0 justify-content-center text-light ">
    <footer>
        <div class="row my-5 justify-content-center py-5">
            <div class="col-11">
                <div class="row ">
                    <div class="col-xl-8 col-md-4 col-sm-4 col-12 my-auto mx-auto a">
                        <h3 class="text-muted mb-md-0 mb-5 bold-text">Jomial.</h3>
                    </div>
                    <div class="col-xl-2 col-md-4 col-sm-4 col-12">
                        <h6 class="mb-3 mb-lg-4 bold-text "><b>MENU</b></h6>
                        <ul class="list-unstyled">
                            <li>Home</li>
                            <li>About</li>
                            <li>Blog</li>
                           
                        </ul>
                    </div>
                    <div class="col-xl-2 col-md-4 col-sm-4 col-12">
                        <h6 class="mb-3 mb-lg-4 text-muted bold-text mt-sm-0 mt-5"><b>Direccion</b></h6>
                        <p class="mb-1">6,Legaño Kalea</p>
                        <p>Berriz,Vizcaya</p>
                    </div>
                </div>
                <div class="row ">
                    <div class="col-xl-8 col-md-4 col-sm-4 col-auto my-md-0 mt-5 order-sm-1 order-3 align-self-end">
                        <p class="social text-muted mb-0 pb-0 bold-text"> <span class="mx-2"><i class="fa fa-facebook" aria-hidden="true"></i></span> <span class="mx-2"><i class="fa fa-linkedin-square" aria-hidden="true"></i></span> <span class="mx-2"><i class="fa fa-twitter" aria-hidden="true"></i></span> <span class="mx-2"><i class="fa fa-instagram" aria-hidden="true"></i></span> </p><small class="rights"><span>&#174;</span> Jomial All Rights Reserved.</small>
                    </div>
                    <div class="col-xl-2 col-md-4 col-sm-4 col-auto order-1 align-self-end ">
                        <h6 class="mt-55 mt-2 text-muted bold-text"><b>Contacto</b></h6><small> <span><i class="fa fa-envelope" aria-hidden="true"></i></span>jomial@gmail.com</small>
                    </div>
                    <div class="col-xl-2 col-md-4 col-sm-4 col-auto order-2 align-self-end mt-3 ">
                        <h6 class="text-muted bold-text"><b>Contacto Importante</b></h6><small><span><i class="fa fa-envelope" aria-hidden="true"></i></span> jomial@uni.eus</small>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</div>
<script type="text/javascript">
    window.onscroll = function () { myFunction() };

    var header = document.getElementById("myHeader");
    var sticky = header.offsetTop;

    function myFunction() {
        if (window.pageYOffset > sticky) {
            header.classList.add("sticky");
        } else {
            header.classList.remove("sticky");
        }
    }
</script>

Jomial_Proiektua/Jomial_Final/Views/Bilatu/Hotel.cshtml
<title>Reserva tu Hotel </title>
@model IEnumerable<Jomial_Final.Models.Hotel>

<link rel="stylesheet" href="~/Content/stylesHotel.css">
<header id="myHeader">
    <nav class="navbar navbar bg justify-content-between">
        <a class="navbar-brand"  href="@Url.Action("IndexLog", "Home")"><img src="~/Imagenes/logo.png"></a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("allBooks", "Bilatu" ,  new {email =Session["erabiltzailea_emaila"]})"> <strong>  @Session["erabiltzaile"] </strong></a>
                <a class="nav-link" href="@Url.Action("Index", "Home")">Cerrar Sesion</a>
            </li>
        </ul>
    </nav>
</header>

@foreach (var item in Model)
{
<div class="containerhandia">


    <h3 id="test">@Html.DisplayFor(modelItem => item.izena)</h3>
    <div>
        <img class="estrella" src="~/Imagenes/iconfinder_star_326703 (1).png"><span>
            <strong>@Html.DisplayFor(modelItem => item.izarrak)</strong> ·
            <u>@Html.DisplayFor(modelItem => item.kokalekua)</u> ·
            <u>@Html.DisplayFor(modelItem => item.distantzia)</u> ·
            <u>@Html.DisplayFor(modelItem => item.kalifikazioa)</u>
        </span>
    </div>
    <div class="top">
        @{
            var contadorea = 0;
        }
        <ul>
            @for (var i = 1; i < item.argazkiak.Count(); i++)
            {
                <li>
                    @{
                        var fuente = item.argazkiak[i].argazkia + ".png";
                        contadorea = contadorea + 1;

                    }
                    <a href="#@contadorea">
                        <img src="~/Imagenes/FotosHotel/@fuente">
                    </a>
                </li>
                <a href="#_3" class="lightbox trans" id="@contadorea">
                    <img src="~/Imagenes/FotosHotel/@fuente">
                </a>

            }
        </ul>



    </div>
    @using (Html.BeginForm("Txartela", "Bilatu"))
    {
        @Html.AntiForgeryToken()
        <form onSubmit = "return checkPassword(this)">
            <div class="busqueda" id="myDiv">
                <h2>Agrega las fechas para ver los precios</h2><br>
                <table>
                    <tr>
                        <th>Fecha de entrada</th>
                        <th>Fecha de salida</th>
                        <th>Habitacion</th>
                    </tr>

                    <tr>
                        <td> <input type="text" class="other-input" onfocus="(this.type='date')" placeholder="Fecha de llegada" name="dataIn" id="dataIn" required></td>
                        <td>
                            <input type="text" class="other-input" onfocus="(this.type='date')" placeholder="Fecha de salida" name="dataOut" id="dataOut" required>
                        </td>
                        <td>
                            <input readonly type="text" class="other-input" placeholder="Habitacion" name="price" id="mytext" required>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <label for="browser">Huespedes:</label>
                            <input id="browser" type="number" required>
                           
                        </td>
                    </tr>
                    <tr>
                    </tr>
                </table><br>
                <button type="submit" id="boton">Adelante</button>
                <input type="hidden" id="days" name="days" />
                <div class="alerta" id="alert">Fechas Incorrectas!</div>
            </div>
        </form>
    }
    <div class="containerTxikia">
        <h4><a href="#habitacion"><strong>Disponemos de varias habitaciones</strong></a></h4>
        <h8>@Html.DisplayFor(modelItem => item.infoGenerala) </h8>
        <hr>
        <section>

            <h4><strong>Servicios</strong></h4><br>
            <div>

                <ul class="check-list">
                    @for (var i = 0; i < item.zerbitzuak.Count(); i++)
                    {
                        <li>@Html.DisplayFor(o => item.zerbitzuak[i])</li>
                    }

                </ul>

            </div>

        </section>
        <hr>
        <h8>
            @Html.DisplayFor(modelItem => item.info)
        </h8>
        <hr>
        <h4><strong>Ubicacion</strong></h4>
        <h8>
            @Html.DisplayFor(modelItem => item.helbidea) ,  @Html.DisplayFor(modelItem => item.kokalekua) , @Html.DisplayFor(modelItem => item.herrialdea)
        </h8>
        <div id="map">

        </div><br>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d46486.91698136041!2d-2.9685838215031417!3d43.26331815882461!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd4e4e27664b89b9%3A0x6534acc41e95a645!2sBilbao%2C%20Vizcaya!5e0!3m2!1ses!2ses!4v1611742883581!5m2!1ses!2ses"
                width="900" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false"
                tabindex="0"></iframe>

        <hr>
        <h4 id="habitacion"><strong>Habitaciones</strong></h4><br>

        <div>

            @for (var i = 0; i < item.gelak.Count(); i++)
            {

                <span class="b"><strong><a href="javascript:putGela()" id="test2">@Html.DisplayFor(modelItem => item.gelak[i].kostuGaua)</a></strong><br>@Html.DisplayFor(modelItem => item.gelak[i].tamaina)</span>

            }

        </div>

    </div>
</div>
}
<div class="container-fluid pb-0 mb-0 justify-content-center text-light ">
    <footer>
        <div class="row my-5 justify-content-center py-5">
            <div class="col-11">
                <div class="row ">
                    <div class="col-xl-8 col-md-4 col-sm-4 col-12 my-auto mx-auto a">
                        <h3 class="text-muted mb-md-0 mb-5 bold-text">Jomial.</h3>
                    </div>
                    <div class="col-xl-2 col-md-4 col-sm-4 col-12">
                        <h6 class="mb-3 mb-lg-4 bold-text "><b>MENU</b></h6>
                        <ul class="list-unstyled">
                            <li>Home</li>
                            <li>About</li>
                            <li>Blog</li>

                        </ul>
                    </div>
                    <div class="col-xl-2 col-md-4 col-sm-4 col-12">
                        <h6 class="mb-3 mb-lg-4 text-muted bold-text mt-sm-0 mt-5"><b>Direccion</b></h6>
                        <p class="mb-1">6,Legaño Kalea</p>
                        <p>Berriz,Vizcaya</p>
                    </div>
                </div>
                <div class="row ">
                    <div class="col-xl-8 col-md-4 col-sm-4 col-auto my-md-0 mt-5 order-sm-1 order-3 align-self-end">
                        <p class="social text-muted mb-0 pb-0 bold-text"> <span class="mx-2"><i class="fa fa-facebook" aria-hidden="true"></i></span> <span class="mx-2"><i class="fa fa-linkedin-square" aria-hidden="true"></i></span> <span class="mx-2"><i class="fa fa-twitter" aria-hidden="true"></i></span> <span class="mx-2"><i class="fa fa-instagram" aria-hidden="true"></i></span> </p><small class="rights"><span>&#174;</span> Jomial All Rights Reserved.</small>
                    </div>
                    <div class="col-xl-2 col-md-4 col-sm-4 col-auto order-1 align-self-end ">
                        <h6 class="mt-55 mt-2 text-muted bold-text"><b>Contacto</b></h6><small> <span><i class="fa fa-envelope" aria-hidden="true"></i></span>jomial@gmail.com</small>
                    </div>
                    <div class="col-xl-2 col-md-4 col-sm-4 col-auto order-2 align-self-end mt-3 ">
                        <h6 class="text-muted bold-text"><b>Contacto Importante</b></h6><small><span><i class="fa fa-envelope" aria-hidden="true"></i></span> jomial@uni.eus</small>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</div>
<script>
    window.onscroll = function () { myFunction() };

    var header = document.getElementById("myHeader");
    var div = document.getElementById("myDiv");
    var sticky = header.offsetTop;
    var stickyDiv = div.offsetTop;

    function myFunction() {
        if (window.pageYOffset > sticky) {
            header.classList.add("sticky");
        } else {
            header.classList.remove("sticky");
        }
        if (window.pageYOffset > stickyDiv) {
            div.classList.add("sticky2");
        } else {
            div.classList.remove("sticky2");
        }
    }

    function putGela() {
     
        var node = document.getElementById('test');
      
        textContent = node.textContent;


        var node2 = document.getElementById('test2');

        textContent2 = node2.textContent;

        document.getElementById("mytext").value = textContent + " - " + textContent2;
    }

    $("input[type=number]").click(function () {
        const date1 = document.getElementById("dataIn").value;
        const date2 = document.getElementById("dataOut").value;
     

        const oneDay = 24 * 60 * 60 * 1000; // hours*minutes*seconds*milliseconds

        var mdy = date1.split('-');
        var mdy1 = date2.split('-');
        const d1 = new Date(mdy[0], mdy[1], mdy[2]);
        const d2 = new Date(mdy1[0], mdy1[1], mdy1[2]);
     
        var element = document.getElementById("alert");

        const diffDays = Math.round(Math.abs((d1 - d2) / oneDay));

      
        if (date1 > date2) {
            element.classList.add("alert-message");
            document.getElementById("boton").disabled = true;
        
        } else {
            document.getElementById("days").value = diffDays;
            element.classList.remove("alert-message");
            document.getElementById("boton").disabled = false;

        }

    });

 

</script>

Jomial_Proiektua/Jomial_Final/Views/Bilatu/allBooks.cshtml
<link rel="stylesheet" href="~/Content/stylesBook.css">
<title>Completa tu Reserva</title>
@model IEnumerable<Jomial_Final.Models.Errenta>
<header id="myHeader">
    <nav class="navbar navbar bg justify-content-between">
        <a class="navbar-brand" href="@Url.Action("IndexLog", "Home")"><img src="~/Imagenes/logo.png"></a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link"><strong>  @Session["erabiltzaile"] </strong></a>
                <a class="nav-link" href="@Url.Action("Index", "Home")">Cerrar Sesion</a>
            </li>
        </ul>
    </nav>
</header>
<div class="mensajea">
    <h1>
        SE HA COMPLETADO TU RESERVA
    </h1><br>
    <h4>Gracias por confiar en nosotros</h4>
</div>
@foreach (var item in Model)
{
    <div class="pricing-box-container">
        <div class="pricing-box text-center">
            <h5>@Html.DisplayFor(modelItem => item.hotel_izena)</h5>
            <p class="price"><sup>€</sup>@Html.DisplayFor(modelItem => item.prezio_total)<sub>/noche</sub></p>
            <ul class="features-list">
                <li><strong>Fecha de entrada: </strong> @Html.DisplayFor(modelItem => item.hasiera_data)</li>
                <li><strong>Fecha de salida: </strong>  @Html.DisplayFor(modelItem => item.amaiera_data)</li>
                <li><strong>Correo electronico: </strong> @Html.DisplayFor(modelItem => item.emaila)</li>
            </ul>

        </div>
    </div>
}